global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: "office_climate"
    static_configs:
      - targets: ["localhost:7979"]
        labels:
          source: "json_exporter"