FROM python:latest
WORKDIR /app

# Install the application dependencies
COPY app /app
#COPY requirements.txt /
RUN pip install --no-cache-dir -r requirements.txt

# Copy in the source code
#COPY . /src
EXPOSE 5000

# Setup an app user so the container doesn't run as the root user
RUN useradd app
USER app

CMD ["fastapi", "dev", "/app/app.py"]